name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: |
        echo "qwe"
        docker -v
        echo ${{secrets.DOCKER_USER}}
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/php7.4:latest
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/php7.4
