name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "test"
      shell: bash
      run: echo ${{secrets.DOCKER_USER}}
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: sudo docker login -u {{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/php7.4:latest
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/php7.4
